cirrus_wheels_macos_arm64_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:14
  matrix:
    - env:
       CIBW_BUILD: cp39-* cp310-*
    - env:
        CIBW_BUILD: cp311-* cp312-*
  env:
    PATH: /opt/homebrew/opt/python@3.10/bin:$PATH
    CIBW_PRERELEASE_PYTHONS: True
    CIBW_ENVIRONMENT: >
      MACOSX_DEPLOYMENT_TARGET=12.0
      _PYTHON_HOST_PLATFORM="macosx-12.0-arm64"             
      PIP_EXTRA_INDEX_URL=https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
      PIP_PRE=1
    PKG_CONFIG_PATH: /opt/arm64-builds/lib/pkgconfig
    CMAKE_PREFIX_PATH: /opt/arm64-builds/
    REPAIR_PATH: /usr/local/gfortran/lib:/opt/arm64-builds/lib
    CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
      DYLD_LIBRARY_PATH=/usr/local/gfortran/lib:/opt/arm64-builds/lib delocate-listdeps {wheel} &&
      DYLD_LIBRARY_PATH=/usr/local/gfortran/lib:/opt/arm64-builds/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}

  install_pre_requirements_script:
    - brew install python@3.10
    - ln -s python3 /opt/homebrew/opt/python@3.10/bin/python

  build_script:
    - which python
    - git submodule update --init
    - uname -m
    - python -c "import platform;print(platform.python_version());print(platform.system());print(platform.machine())"
    - clang --version

  install_cibuildwheel_script:
    - python -m pip install cibuildwheel==2.14.1

  cibuildwheel_script:
    - cibuildwheel

  wheels_artifacts:
    path: "wheelhouse/*"
